Appointment endpoints
LucaStefan112/MedConnect-Server pull request #22
Opened 2023-03-18 17:36 UTC by MariusAchitei

2023-03-18 20:16 UTC, LucaStefan112 requested changes

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  if (currentUser == null) {
use === insead of ==

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
you take the id from the response object?

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +    res.send({
use the methods like this: res.status(404).send(...)

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  res.send({ succes: true, message: appointments });
again, call each method by the returned object of the last one: res.status(200).send(...)

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +export const postAppointment = async (req: Request, res: Response) => {
postAppointment -> addAppointment

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
you take the id from the response object?

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  res.send({ succes: true, message: newAppointent });
add a status to the response

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
again with the response object

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const currentApp = await Appointment.findById(appId);
currentApp -> currentAppointment

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  if (currentApp == null) {
use === instead of ==

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +    res.send({
again, format them as one after the other

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  if (!currentApp.patient == id && currentApp.patient == id) {
use === insead of ==
And what is this line of code doing exactly?

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      res.send({
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      console.log("Cause: unauthorized");
The user should not get here without a token, so we assume the if the client got to this step he is already authorized

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +          "Refused the getting of an appointment\n" + "Cause: unauthorized",
just "Unauthorized"

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  res.send({ succes: true, message: currentApp });
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      console.log("Cause: unauthorized");
just 'Unauthoried'

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  if (!currentApp.patient == id && currentApp.patient == id) {
=== instead of ==

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
from response?

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +    res.send({
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      res.send({
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  res.send({ succes: true, message: "Deactivated appointment" });
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  currentApp.isActive = false;
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  const currentApp = await Appointment.findById(appId);
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +    res.send({
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  if (!currentApp.patient == id && currentApp.patient == id) {
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      console.log("Cause: unauthorized");
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +          "Refused the deletion of an appointment\n" + "Cause: unauthorized",
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +      res.send({
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/controllers/appointments.controller.ts
> +  res.send({ succes: true, message: "Deleted appointment" });
again

2023-03-18 20:16 UTC, LucaStefan112 commented on src/index.ts
> +import { limiter } from "./middlewares/limiter";
imports to the top

2023-03-18 20:16 UTC, LucaStefan112 commented on src/index.ts
> +import appointmentRouter from "./routes/appointment";
imports to the top

2023-03-18 20:16 UTC, LucaStefan112 commented on src/middlewares/validation.ts
> +  console.log(token);
remove log

2023-03-18 20:16 UTC, LucaStefan112 commented on src/middlewares/validation.ts
> +  const { token } = req.params;
the token should be taken from the cookie

2023-03-18 20:16 UTC, LucaStefan112 commented on src/models/appointment.ts
> +  patient: string;
implement a patient interface

2023-03-18 20:16 UTC, LucaStefan112 commented on src/models/appointment.ts
> +  doctor: string;
implement a doctor interface

2023-03-18 20:16 UTC, LucaStefan112 commented on src/routes/appointment.ts
> +import { validateToken } from "../middlewares/validation";
imports at the top

2023-03-18 20:16 UTC, LucaStefan112 commented on src/routes/appointment.ts
> +import {
at the top

2023-03-18 20:16 UTC, LucaStefan112 commented on src/routes/appointment.ts
> +appointmentRouter.use("/:token", validateToken);
validate token should be used by the app object

2023-03-19 11:36 UTC, MariusAchitei commented on src/controllers/appointments.controller.ts
> +  const { id } = res.locals.user;
Asa nu mi da eroare ca la Omer de aia automata, e il setez cand se verifica tokenu si e mai simplu :)))

2023-03-20 10:47 UTC, LucaStefan112 approved these changes

2023-03-20 10:47 UTC, merged